/* ================================================
 * @Class Name => CreditInquiryHTTPCallOutConstant
 * @author => Admin
 * @purpose=> 
 * @created date=> 
 * @last modified date=> 
 * @last modified by => 
 ================================================*/
public with sharing class CreditInquiryHTTPCallOutConstant {
    public final static String SPACE = ' ';
    public final static String PLUS = '+';
    public final static String DIAL = 'DIAL';
    public final static String CERR = 'CERR';
    public final static String BLANK = 'BLANK'; 
    public final static String RIGTH = 'R';   
    public final static String REQ = 'R';
    public final static String REQUIRED = 'REQUIRED';
}