/* ================================================
 * @Class Name => CreditInquiryHTTPCallOutConstant
 * @author => Admin
 * @purpose=> 
 * @created date=> 
 * @last modified date=> 
 * @last modified by => 
 ================================================*/
public with sharing class CreditInquiryHTTPCallOutConstant {
    public final static String SPACE = ' ';
    public final static String PLUS = '+';
    public final static String CERR = 'CERR';
}
