/* ================================================
 * @Class Name => PayOrLogicConstants
 * @author => Admin
 * @purpose=> 
 * @created date=> 
 * @last modified date=> 
 * @last modified by => 
 ================================================*/
public class PayOrLogicConstants {
    public static final String GUARANTOR = 'Guarantor';
    public static final String INDIVIDUALS = 'Individuals';
    public static final String INSURANCEFINDER = 'InsuranceFinder';
    public static final String TRANSACTIONID = 'TransactionId';
    public static final String RESPONSEDATE = 'ResponseDate';
    public static final String TECHNICALEXCEPTIONMESSAGE = 'TechnicalExceptionMessage';
    public static final String STATUS = 'Status';
    public static final String COMPLETED = 'Completed';
    public static final String FAILED = 'Failed';
    public static final String PAYORLOGIC = 'PayOrLogic';
    public static final String PRODUCTDATA = 'productData';
    public static final String DEMOGRAPHIC = 'Demographic';
    public static final String REQUESTDATE = 'RequestDate';
    public static final String REQUESTINGSOFTWARE = 'RequestingSoftware';
    public static final String REQUIRED = 'Required';
    public static final String USEREXCEPTIONMESSAGE = 'UserExceptionMessage';
    public static final String DATEFORMAT = 'MM/dd/yyyy\' \'HH:mm:ss';
    public static final String JSONREQUEST = 'jsonRequest';
}